/// <auto-generated>
/// Generated by QfStudio.Godette.ReactiveUI.ReactiveNodeCodeEmitter.
/// </auto-generated>
#nullable enable

using System.ComponentModel;
using ReactiveUI;

namespace QfStudio.Godette.ReactiveUI;

public class ReactiveSpinBox : global::Godot.SpinBox, IActivatableView, IReactiveObject
{
    public event PropertyChangedEventHandler? PropertyChanged;
    public event PropertyChangingEventHandler? PropertyChanging;
    void IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args) => PropertyChanged?.Invoke(this, args);
    void IReactiveObject.RaisePropertyChanging(PropertyChangingEventArgs args) => PropertyChanging?.Invoke(this, args);

    private object? _viewModel;
    public object? ViewModel
    {
        get => _viewModel;
        set => this.RaiseAndSetIfChanged(ref _viewModel, value);
    }
}

public class ReactiveSpinBox<T> : ReactiveSpinBox, IViewFor<T> where T : class
{
	public new T? ViewModel
	{
	    get => base.ViewModel as T;
	    set => base.ViewModel = value;
	}
}