/// <auto-generated>
/// Generated by QfStudio.Godette.ReactiveUI.ReactiveNodeCodeEmitter.
/// </auto-generated>
#nullable enable

using System.ComponentModel;
using ReactiveUI;

namespace QfStudio.Godette.ReactiveUI;

public class ReactiveOptionButton<T> : global::Godot.OptionButton, IViewFor<T>, IActivatableView, IReactiveObject where T : class
{
    public event PropertyChangedEventHandler? PropertyChanged;
    public event PropertyChangingEventHandler? PropertyChanging;
    void IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args) => PropertyChanged?.Invoke(this, args);
    void IReactiveObject.RaisePropertyChanging(PropertyChangingEventArgs args) => PropertyChanging?.Invoke(this, args);

    private T? _viewModel;
    public T? ViewModel
    {
        get => _viewModel;
        set => this.RaiseAndSetIfChanged(ref _viewModel, value);
    }
    
    object? IViewFor.ViewModel
	{
	    get => ViewModel;
	    set => ViewModel = (T?)value;
	}
}

public class ReactiveOptionButton : ReactiveOptionButton<object>
{
}
