/// <auto-generated>
/// Generated by QfStudio.Godotte.ReactiveUI.ReactiveNodeCodeEmitter.
/// </auto-generated>
#nullable enable

using System.Reactive.Disposables;
using ReactiveUI;

namespace QfStudio.Godotte.ReactiveUI;

public class ReactiveTree : global::Godot.Tree, IActivatable
{
    private readonly CompositeDisposable _disposables = new();
    private readonly List<Action<CompositeDisposable>> _blocks = [];

	public ReactiveTree() 
	{
		TreeEntered += OnTreeEntered;
		TreeExited += OnTreeExited;
		Ready += OnReady;
	}

    public bool IsActivated { get; private set; }

    public global::Godot.GodotSynchronizationContext UiContext => ActivationContextProvider.UiContext;

    public void Activate()
    {
        if (IsActivated) return;

        IsActivated = true;
        foreach (var block in _blocks)
        {
            ActivateSingleBlock(block);
        }
    }

    private void ActivateSingleBlock(Action<CompositeDisposable> block)
    {
        var disposable = new CompositeDisposable();
        block(disposable);
        _disposables.Add(disposable);
    }

    public void Deactivate()
    {
        if (!IsActivated) return;

        _disposables.Clear();
        IsActivated = false;
    }

    public void WhenActivated(Action<CompositeDisposable> block)
    {
        _blocks.Add(block);

        if (IsActivated)
        {
            ActivateSingleBlock(block);
        }
    }

	private void OnTreeEntered()
	{
		if (IsNodeReady()) {
			Activate();
		}
	}

    private void OnReady()
    {
        Activate();
    }

    private void OnTreeExited()
    {
        Deactivate();
    }
}

public class ReactiveTree<T> : ReactiveTree, IViewFor<T> where T : class 
{
    object? IViewFor.ViewModel
    {
        get => ViewModel;
        set => ViewModel = value as T;
    }

    public T? ViewModel { get; set; }
}