/// <auto-generated>
/// Generated by QfStudio.Godette.ReactiveUI.ReactiveNodeCodeEmitter.
/// </auto-generated>
#nullable enable

using System.Reactive.Disposables;
using ReactiveUI;

namespace QfStudio.Godette.ReactiveUI;

public class ReactiveLabel : global::Godot.Label, IActivatable, IViewFor
{
    private readonly CompositeDisposable _disposables = new();
    private readonly List<Action<CompositeDisposable>> _blocks = [];

	public ReactiveLabel() 
	{
		TreeEntered += OnTreeEntered;
		TreeExited += OnTreeExited;
		Ready += OnReady;
	}
	
	public object? ViewModel { get; set; }
    
    public bool IsActivated { get; private set; }

    public global::Godot.GodotSynchronizationContext UiContext => ActivationContextProvider.UiContext;

    public void Activate()
    {
        if (IsActivated) return;

        IsActivated = true;
        foreach (var block in _blocks)
        {
            ActivateSingleBlock(block);
        }
    }

    private void ActivateSingleBlock(Action<CompositeDisposable> block)
    {
        var disposable = new CompositeDisposable();
        block(disposable);
        _disposables.Add(disposable);
    }

    public void Deactivate()
    {
        if (!IsActivated) return;

        _disposables.Clear();
        IsActivated = false;
    }

    public void WhenActivated(Action<CompositeDisposable> block)
    {
        _blocks.Add(block);

        if (IsActivated)
        {
            ActivateSingleBlock(block);
        }
    }

	private void OnTreeEntered()
	{
		if (IsNodeReady()) {
			Activate();
		}
	}

    private void OnReady()
    {
        Activate();
    }

    private void OnTreeExited()
    {
        Deactivate();
    }
}

public class ReactiveLabel<T> : ReactiveLabel, IViewFor<T> where T : class 
{
	public new T? ViewModel
	{
	    get => base.ViewModel as T;
	    set => base.ViewModel = value;
	}
}