/// <auto-generated>
/// Generated by QfStudio.Godette.ReactiveUI.ReactiveNodeCodeEmitter.
/// </auto-generated>
#nullable enable

using System.ComponentModel;
using System.Reactive.Disposables;
using ReactiveUI;

namespace QfStudio.Godette.ReactiveUI;

public class ReactiveItemList : global::Godot.ItemList, IActivatableView, IReactiveObject
{
    private readonly CompositeDisposable _disposables = new();
    private readonly List<Action<CompositeDisposable>> _blocks = [];

    public event PropertyChangedEventHandler? PropertyChanged;
    public event PropertyChangingEventHandler? PropertyChanging;
    void IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args) => PropertyChanged?.Invoke(this, args);
    void IReactiveObject.RaisePropertyChanging(PropertyChangingEventArgs args) => PropertyChanging?.Invoke(this, args);

	public ReactiveItemList()
	{
		TreeEntered += OnTreeEntered;
		TreeExited += OnTreeExited;
		Ready += OnReady;
	}

    private object? _viewModel;
    public object? ViewModel
    {
        get => _viewModel;
        set => this.RaiseAndSetIfChanged(ref _viewModel, value);
    }

    public bool IsActivated { get; private set; }

    public void Activate()
    {
        if (IsActivated) return;

        IsActivated = true;
        foreach (var block in _blocks)
        {
            ActivateSingleBlock(block);
        }
    }

    private void ActivateSingleBlock(Action<CompositeDisposable> block)
    {
        var disposable = new CompositeDisposable();
        block(disposable);
        _disposables.Add(disposable);
    }

    public void Deactivate()
    {
        if (!IsActivated) return;

        _disposables.Clear();
        IsActivated = false;
    }

    public void WhenActivated(Action<CompositeDisposable> block)
    {
        _blocks.Add(block);

        if (IsActivated)
        {
            ActivateSingleBlock(block);
        }
    }

	private void OnTreeEntered()
	{
		if (IsNodeReady()) {
			Activate();
		}
	}

    private void OnReady()
    {
        Activate();
    }

    private void OnTreeExited()
    {
        Deactivate();
    }
}

public class ReactiveItemList<T> : ReactiveItemList, IViewFor<T> where T : class 
{
	public new T? ViewModel
	{
	    get => base.ViewModel as T;
	    set => base.ViewModel = value;
	}
}