using System.Runtime.CompilerServices;

namespace QfStudio.Godotte.ReactiveUI;

// TODO Use C#14 .NET 10 file-based app feature
// https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/#building-and-running-c-programs

/// <remarks>
/// I've now come to realize the ultimate truth about source generators:
/// the best one is neither ISourceGenerator nor IIncrementalGenerator,
/// but rather one that simply writes out the code files directly.
/// </remarks>
public static class ReactiveNodeCodeEmitter
{
	private static string Namespace => "QfStudio.Godotte.ReactiveUI";

	private static string[] TypesToTransform => [
		"Node",
		"Control",
		"TabContainer",
		"Window",
		"CanvasLayer"
	];

	private static bool DryRun { set; get; }

	private static string GetBasePath([CallerFilePath] string path = "")
	{
		return path;
	}

	public static void Main(string[] args)
	{
		DryRun = !args.Contains("--confirm");
		if (DryRun)
		{
			Console.WriteLine("Dry run: no file is written.");
		}

		var baseDir = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(GetBasePath()) ?? ".", "../QfStudio.Godette.ReactiveUI/Nodes"));

		Directory.CreateDirectory(baseDir);
		foreach (var type in TypesToTransform)
		{
			CreateSourceFile(baseDir, type);
		}
	}

	private static void CreateSourceFile(string baseDir, string typeName)
	{
		var filePath = Path.GetFullPath(Path.Combine(baseDir, $"Reactive{typeName}.g.cs"));

		var originalSource = string.Empty;
		if (File.Exists(filePath))
		{
			originalSource = File.ReadAllText(filePath);
		}

		var newSource = GetSourceText(typeName);
		if (originalSource != newSource)
		{
			Console.WriteLine($"Creating source file for {typeName}: {filePath}");
			if (!DryRun)
				File.WriteAllText(filePath, newSource);
		}
	}

	private static string GetSourceText(string typeName) =>
		$$"""
/// <auto-generated>
/// Generated by {{typeof(ReactiveNodeCodeEmitter).FullName}}.
/// </auto-generated>

using System.Reactive.Disposables;

namespace {{Namespace}};

public partial class Reactive{{typeName}} : global::Godot.{{typeName}}, IActivatable
{
    private readonly CompositeDisposable _disposables = new();
    private readonly List<Action<CompositeDisposable>> _blocks = [];

	public Reactive{{typeName}}() 
	{
		TreeEntered += OnTreeEntered;
		TreeExited += OnTreeExited;
		Ready += OnReady;
	}

    public bool IsActivated { get; private set; }

    public global::Godot.GodotSynchronizationContext UiContext => ActivationContextProvider.UiContext;

    public void Activate()
    {
        if (IsActivated) return;

        IsActivated = true;
        foreach (var block in _blocks)
        {
            ActivateSingleBlock(block);
        }
    }

    private void ActivateSingleBlock(Action<CompositeDisposable> block)
    {
        var disposable = new CompositeDisposable();
        block(disposable);
        _disposables.Add(disposable);
    }

    public void Deactivate()
    {
        if (!IsActivated) return;

        _disposables.Clear();
        IsActivated = false;
    }

    public void WhenActivated(Action<CompositeDisposable> block)
    {
        _blocks.Add(block);

        if (IsActivated)
        {
            ActivateSingleBlock(block);
        }
    }

	private void OnTreeEntered()
	{
		if (IsNodeReady()) {
			Activate();
		}
	}

    private void OnReady()
    {
        Activate();
    }

    private void OnTreeExited()
    {
        Deactivate();
    }
}
""";
}
